trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: airpods-site

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'ACR-ServiceConnection'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: latest

- task: KubernetesManifest@1
  inputs:
    action: deploy
    kubernetesServiceConnection: 'AKS-ServiceConnection'
    manifests: |
      deployment.yaml
      service.yaml
